"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.STANDARD_AXES_MAPPING = exports.STANDARD_AXES = exports.STANDARD_BUTTON_MAPPING = exports.STANDARD_BUTTONS = void 0;
exports.STANDARD_BUTTONS = {
    RC_BOTTOM: 'RC_BOTTOM',
    RC_RIGHT: 'RC_RIGHT',
    RC_LEFT: 'RC_LEFT',
    RC_TOP: 'RC_TOP',
    BUMPER_LEFT: 'BUMPER_LEFT',
    BUMPER_RIGHT: 'BUMPER_RIGHT',
    TRIGGER_LEFT: 'TRIGGER_LEFT',
    TRIGGER_RIGHT: 'TRIGGER_RIGHT',
    CC_LEFT: 'CC_LEFT',
    CC_RIGHT: 'CC_RIGHT',
    THUMBSTICK_LEFT: 'THUMBSTICK_LEFT',
    THUMBSTICK_RIGHT: 'THUMBSTICK_RIGHT',
    LC_BOTTOM: 'LC_BOTTOM',
    LC_RIGHT: 'LC_RIGHT',
    LC_LEFT: 'LC_LEFT',
    LC_TOP: 'LC_TOP',
    CC_CENTER: 'CC_CENTER', // Center button in center cluster
};
exports.STANDARD_BUTTON_MAPPING = {
    RC_BOTTOM: 0,
    RC_RIGHT: 1,
    RC_LEFT: 2,
    RC_TOP: 3,
    BUMPER_LEFT: 4,
    BUMPER_RIGHT: 5,
    TRIGGER_LEFT: 6,
    TRIGGER_RIGHT: 7,
    CC_LEFT: 8,
    CC_RIGHT: 9,
    THUMBSTICK_LEFT: 10,
    THUMBSTICK_RIGHT: 11,
    LC_BOTTOM: 12,
    LC_RIGHT: 13,
    LC_LEFT: 14,
    LC_TOP: 15,
    CC_CENTER: 16,
};
exports.STANDARD_AXES = {
    THUMBSTICK_LEFT_X: 'THUMBSTICK_LEFT_X',
    THUMBSTICK_LEFT_Y: 'THUMBSTICK_LEFT_Y',
    THUMBSTICK_RIGHT_X: 'THUMBSTICK_RIGHT_X',
    THUMBSTICK_RIGHT_Y: 'THUMBSTICK_RIGHT_Y', // Vertical axis for right stick (negative up/positive down)
};
exports.STANDARD_AXES_MAPPING = {
    THUMBSTICK_LEFT_X: 0,
    THUMBSTICK_LEFT_Y: 1,
    THUMBSTICK_RIGHT_X: 2,
    THUMBSTICK_RIGHT_Y: 3,
};
//# sourceMappingURL=standard-mapping.js.map