export const XR_STANDARD_BUTTONS = {
	TRIGGER: 'TRIGGER',
	SQUEEZE: 'SQUEEZE',
	TOUCHPAD: 'TOUCHPAD',
	THUMBSTICK: 'THUMBSTICK',
	BUTTON_1: 'BUTTON_1',
	BUTTON_2: 'BUTTON_2',
};

export const XR_STANDARD_BUTTON_MAPPING = {
	TRIGGER: 0,
	SQUEEZE: 1,
	TOUCHPAD: 2,
	THUMBSTICK: 3,
	BUTTON_1: 4,
	BUTTON_2: 5,
};

export const XR_STANDARD_AXES = {
	TOUCHPAD_X: 'TOUCHPAD_X',
	TOUCHPAD_Y: 'TOUCHPAD_Y',
	THUMBSTICK_X: 'THUMBSTICK_X',
	THUMBSTICK_Y: 'THUMBSTICK_Y',
};

export const XR_STANDARD_AXES_MAPPING = {
	TOUCHPAD_X: 0,
	TOUCHPAD_Y: 1,
	THUMBSTICK_X: 2,
	THUMBSTICK_Y: 3,
};
